language: python
python:
- '2.7'
before_install:
- chmod +x sys/test.sh
install: pip install -r requirements.txt
script: sys/test.sh
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/b4f3cecdc1bc0e6b6feb
    - https://webhooks.gitter.im/e/86d334546d35356f1c30
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
    secure: LzDEldhNMBkAoh6hOt6eB/87Hi5NXE3rcKk854w3GmkOLgebblhO4b/KHQ459UVnbNnvvnVJyvo+C0qyeN6dOxIg2mcuBih1T5mR499pYSi/CU524oVl3UQpckBFxr8d/00gBCR+p3UbLXiUqQDCrBddglrzEKE0F62fZcHyKB4=

before_script:
  - echo -e "Host xarxa6.unstable.build\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

before_install:
  - pwd
  - openssl aes-256-cbc -k "$super_secret_password" -in ./sys/super_secret.txt.enc -out ./sys/super_secret.txt -d

after_success:
  - chmod 600 ./sys/super_secret.txt # this key should have push access
  - ssh-add ./sys/super_secret.txt
  - git remote add deploy git@xarxa6.unstable.build:/opt/git/xarxa6.git
  - git push deploy
