#! /bin/sh
PATH=/usr/bin
DESC="Xarxa6 analytics api"
NAME=xarxa6-api
DAEMON=/usr/local/bin/$NAME
PIDFILE=/var/run/xarxa6/xarxa6-api.pid
SCRIPTNAME=/etc/init.d/$NAME

do_start()
{
    $DAEMON
    if [ -f "$PIDFILE" ]
    then
        echo "$NAME HAS STARTED"
    else
        echo "$NAME CALLED BUT NO PID WAS FOUND"
        exit 1;
    fi
}

do_stop()
{
    $DAEMON -stop
}

case "$1" in
  start)
    do_start
    ;;

  stop)
    do_stop
    ;;

  status)
    if [ -f "$PIDFILE" ]
    then
        echo 'Xarxa6 API running';
        exit 0;
    else
        echo 'Xarxa6 API NOT running';
        exit 1;
    fi
    ;;

  restart|force-reload)
        do_stop
        do_start
        ;;
esac

:
