#!./flask/bin/python
import traceback

if __name__ == "__main__":
    try:
        import config
        import log
        import dal
        import api
        api.app.run(host = config.bootConfig['host'], port = config.bootConfig['port'])
        log.info("Xarxa6 API has started!")
    except:
        print "Xarxa6 API has NOT started!"
        traceback.print_exc()
